services:
  - type: web
    name: house-rent-app
    env: node
    region: oregon
    plan: starter
    branch: main
    rootDir: backend
    buildCommand: >
      npm install &&
      cd ../frontend && npm install && npm run build &&
      cd ../backend && rm -rf ./public && mkdir -p ./public && cp -r ../frontend/build/* ./public/
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
